import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const hello = trpc.useQuery(["author.hello", { text: "from tRPC" }]);
  const { data: authors } = trpc.useQuery(["author.getAll"]);
  const { data: books } = trpc.useQuery(["book.getAll"]);

  const helloText = hello.data?.greeting || "Loading...";

  return (
    <>
      <Head>
        <title>{helloText}</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center p-4">
        <h1 className="text-5xl font-extrabold leading-normal text-gray-700 md:text-[5rem]">
          {helloText}
        </h1>
        <div className="flex flex-row justify-between gap-32">
          <div className="w-1/2">
            <p className="text-2xl text-gray-700">Books</p>
            {books?.map((book) => (
              <InfoCard
                key={book.id + book.title}
                title={book.title}
                additionalProps={[
                  `BookId: ${book.id.toString()}`,
                  `AuthorId: ${book.authorId.toString()}`,
                  `Published at: ${book?.publishedAt?.toString() || ""}`,
                  `Created at: ${book?.createdAt?.toString()}`,
                ]}
              />
            ))}
          </div>
          <div className="w-1/2">
            <p className="text-2xl text-gray-700">Authors</p>
            {authors?.map((author) => (
              <InfoCard
                key={author.id + author.name}
                title={author.name}
                additionalProps={[
                  `AuthorId: ${author.id.toString()}`,
                  `Email: ${author.email}`,
                  `Birth Country: ${author.birthCounty}`,
                ]}
              />
            ))}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

type InfoCardProps = {
  title: string;
  additionalProps: string[];
};

const InfoCard = ({ title, additionalProps }: InfoCardProps) => {
  return (
    <section className="mb-4 flex flex-col justify-center rounded border-2 border-gray-500 p-6 shadow-xl duration-500 motion-safe:hover:scale-105">
      <h2 className="text-lg text-gray-700">{title}</h2>
      <ul className="mt-3">
        {additionalProps.map((prop, index) => (
          <li key={index + prop} className="text-sm text-gray-600">
            {prop}
          </li>
        ))}
      </ul>
    </section>
  );
};
